// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtpMYgeRyS3phrqpJAsooaTSU7nFspFpA',
    appId: '1:34648232424:web:8075842fe539b56cf9945d',
    messagingSenderId: '34648232424',
    projectId: 'hiklik-sports-76bdd',
    authDomain: 'hiklik-sports-76bdd.firebaseapp.com',
    storageBucket: 'hiklik-sports-76bdd.appspot.com',
    measurementId: 'G-ZFQDSKB1WK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxuNQT-1a1i3prLq0gzz91HLtBmB9HKZM',
    appId: '1:34648232424:android:07d92fae4003e2adf9945d',
    messagingSenderId: '34648232424',
    projectId: 'hiklik-sports-76bdd',
    storageBucket: 'hiklik-sports-76bdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUkTFRxXvHbqMEFWLZey22VmT4Q88EBTU',
    appId: '1:34648232424:ios:c98b3a2f693bc248f9945d',
    messagingSenderId: '34648232424',
    projectId: 'hiklik-sports-76bdd',
    storageBucket: 'hiklik-sports-76bdd.appspot.com',
    iosClientId: '34648232424-bcfi1n6qub1us80n1sg8g32hhj98scih.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiklikApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUkTFRxXvHbqMEFWLZey22VmT4Q88EBTU',
    appId: '1:34648232424:ios:c98b3a2f693bc248f9945d',
    messagingSenderId: '34648232424',
    projectId: 'hiklik-sports-76bdd',
    storageBucket: 'hiklik-sports-76bdd.appspot.com',
    iosClientId: '34648232424-bcfi1n6qub1us80n1sg8g32hhj98scih.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiklikApp',
  );
}
